version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongPass123!
    ports:
      - "1433:1433"
    volumes:
      - ./database.sql:/database.sql

  web:
    build: .
    container_name: testqt_web
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:sqlserver://db:1433;databaseName=TestQT_60;encrypt=false;trustServerCertificate=true
      - DB_PASS=StrongPass123!
    depends_on:
      - db
